21 allow to run app from jar
EPAM-Online-Courses/teatrees-jap7 pull request #40
Opened 2022-03-16 08:21 UTC by konopkagrzegorz

We have finished issue with not running app from jar.

We have changed:
- pom.xml - bumped version and added maven-surefile-plugin
- created ExecutableJarIT class with appropriate tests

To run test type in terminal in project's directory where pom.xml is located:
```mvn verify```

Closes #21

2022-03-18 13:47 UTC, pkierat-epam requested changes

2022-03-18 13:47 UTC, pkierat-epam commented on pom.xml
> +                                <exclude>none</exclude>
This is not very useful. Maven is built around "Convention over configuration" principle.

2022-03-18 13:47 UTC, pkierat-epam commented on pom.xml
> +                <artifactId>maven-surefire-plugin</artifactId>
Maven Surefire plugin is used to run unit tests. For IT, the plugin is called Failsafe.

2022-03-18 13:47 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +    static {
Why static initialization block?

2022-03-18 13:47 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +            e.getMessage();
This line does absolutely nothing. (It invokes a method and ignores its result.)

2022-03-18 13:47 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +        List<Path> paths = Files.
This code is duplicated. Please remove the redudancy.

2022-03-18 14:21 UTC, kidolega commented
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.epam.prejap.teatrees.TeaTrees</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

wystarczy taki plugin zeby odpalic to z jara

2022-03-22 08:35 UTC, Nimrud commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +public class ExecutableJarIT {
No javadoc

2022-03-22 08:36 UTC, konopkagrzegorz commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +public class ExecutableJarIT {
Javadoc for Test class?

2022-03-22 08:48 UTC, emmaline261b commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +    private List<Path> findPathsWithExtensions(String path, String extension) throws IOException {
Nice extraction!

2022-03-23 07:04 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +public class ExecutableJarIT {
I see no point in documenting tests, unless there's something non-obvious which needs to be explicitly noted.

2022-03-23 07:04 UTC, pkierat-epam commented on src/test/java/com/epam/prejap/teatrees/ExecutableJarIT.java
> +public class ExecutableJarIT {
I see no point in documenting tests, unless there's something non-obvious which needs to be explicitly noted.

2022-03-23 07:53 UTC, merged